// https_upstream — a handler that calls a third-party HTTPS API without
// blocking its worker (#229): the http1_1/upstream pooled client.
//
// An edge server relays `<METHOD> /up/<path>` to `<METHOD> /<path>` on one
// upstream origin and answers with the upstream's status and body. Each worker
// has its own pool of keep-alive connections to the origin (make_state); the
// handler parks on the pooled socket and the worker keeps serving; the
// continuation relays the answer. One TLS client config (the trusted CAs) is
// shared by every worker. The pool's maintenance timer (on_worker_start)
// enforces the deadlines and closes idle connections; a Resolver thread
// follows DNS changes.
//
// Failures answer 502 (504 for a timeout) with `X-Upstream-Failure: <why>`,
// and 503 when this worker's connections are all busy. (Naming the failure to
// the client is for the demo and its tests; a real service logs it.)
//
// Run (needs Mbed TLS 4 for HTTPS):
//   UPSTREAM_HOST=api.github.com v -d vanilla_tls run examples/https_upstream/src
//   curl -i http://localhost:8096/up/zen
// Plain HTTP upstream:
//   UPSTREAM_HOST=localhost UPSTREAM_PORT=3000 UPSTREAM_HTTPS=0 v run examples/https_upstream/src
module main

import os
import server
import core
import tls
import http1_1.upstream

const edge_port = 8096

const resp_503 = 'HTTP/1.1 503 Service Unavailable\r\nRetry-After: 1\r\nContent-Length: 0\r\n\r\n'
const resp_404 = 'HTTP/1.1 404 Not Found\r\nContent-Length: 0\r\n\r\n'
const resp_ok = 'HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\nok'
const failure_head = 'HTTP/1.1 502 Bad Gateway\r\nContent-Length: 0\r\nX-Upstream-Failure: '
const timeout_head = 'HTTP/1.1 504 Gateway Timeout\r\nContent-Length: 0\r\nX-Upstream-Failure: '
const crlf2 = '\r\n\r\n'
const up_prefix = '/up/'
const user_agent = 'vanilla-https-upstream/1'.bytes()
const fill_prefix = '/fill/'
const max_fill = 0x7fffffff

// failure_names[int(f)] names an upstream.Failure in X-Upstream-Failure.
const failure_names = ['none', 'invalid', 'dns', 'connect', 'tls_verify', 'tls', 'send', 'closed',
	'truncated', 'timeout', 'malformed', 'too_large']

// App is one worker's state: its pool to the upstream origin.
struct App {
mut:
	up &upstream.Pool = unsafe { nil }
}

// new_app builds one worker's state (make_state): the pool, following the
// resolver when there is one.
fn new_app(o upstream.Origin, cfg &tls.Config, r &upstream.Resolver) voidptr {
	mut p := upstream.Pool.new(o, cfg) or { panic(err) }
	if r != unsafe { nil } {
		mut rr := unsafe { r }
		p.follow(mut rr) or { panic(err) }
	}
	return voidptr(&App{
		up: p
	})
}

fn on_worker_start(worker_state voidptr, mut el core.EventLoop) {
	mut app := unsafe { &App(worker_state) }
	app.up.start_maintenance(mut el) or { eprintln(err) }
}

@[inline]
fn wb(mut out []u8, b []u8) {
	unsafe { out.push_many(b.data, b.len) }
}

fn wi(mut out []u8, n int) {
	if n == 0 {
		out << `0`
		return
	}
	mut d := [20]u8{}
	mut i := d.len
	mut v := n
	for v > 0 {
		i--
		d[i] = u8(`0` + v % 10)
		v /= 10
	}
	unsafe { out.push_many(&d[i], d.len - i) }
}

// view is a non-owning string over req[s..s + n] (never kept past the call).
@[inline]
fn view(req []u8, s int, n int) string {
	return if n > 0 { unsafe { tos(&req[s], n) } } else { '' }
}

// leading_int reads the decimal digits that start req[s..s + n], in place: 0
// when there are none, saturating at max_fill (as string.int() does).
@[direct_array_access]
fn leading_int(req []u8, s int, n int) int {
	mut v := 0
	for i in s .. s + n {
		c := req[i]
		if c < `0` || c > `9` {
			break
		}
		d := int(c - `0`)
		if v > (max_fill - d) / 10 {
			return max_fill
		}
		v = v * 10 + d
	}
	return v
}

fn edge(req []u8, mut out []u8, client_fd int, worker_state voidptr, mut el core.EventLoop) core.Step {
	// The request line, as views: METHOD SP target SP version.
	sp1 := index_of(req, 0, ` `)
	sp2 := if sp1 > 0 { index_of(req, sp1 + 1, ` `) } else { -1 }
	if sp2 < 0 {
		core.append_str(mut out, resp_404)
		return .done
	}
	target := view(req, sp1 + 1, sp2 - sp1 - 1)
	if target == '/health' {
		core.append_str(mut out, resp_ok)
		return .done
	}
	// /fill/<n>/<path>: POST <n> generated bytes to /<path> — a request body
	// larger than the edge itself buffers (bodies past 1 MiB are streamed to a
	// handler that cannot park), for the large-body tests.
	mut fill := -1
	mut up_start := sp1 + up_prefix.len // the '/' that starts the upstream target
	if target.starts_with(fill_prefix) {
		slash := index_of(req, sp1 + 1 + fill_prefix.len, `/`)
		if slash < 0 || slash > sp2 {
			core.append_str(mut out, resp_404)
			return .done
		}
		fill = leading_int(req, sp1 + 1 + fill_prefix.len, slash - sp1 - 1 - fill_prefix.len)
		up_start = slash
	} else if !target.starts_with(up_prefix) {
		core.append_str(mut out, resp_404)
		return .done
	}
	mut app := unsafe { &App(worker_state) }
	mut x := app.up.acquire() or {
		core.append_str(mut out, resp_503) // every connection of this worker is busy
		return .done
	}
	// /up/<path> → /<path>: the target from its '/' on, still a view.
	x.request(view(req, 0, sp1), view(req, up_start, sp2 - up_start))
	x.header('User-Agent', user_agent) // many APIs refuse a request without one
	if fill > 0 {
		mut b := x.body()
		for i in 0 .. fill {
			b << u8(`a` + i % 26)
		}
	}
	head_end := index_of_crlf2(req)
	// An Idempotency-Key makes a POST safe to send twice: forward it, and let
	// the pool retry the request once on a fresh connection if its kept one
	// turns out dead before answering.
	ks, kl := field(req, head_end, 'idempotency-key')
	if ks > 0 {
		x.header('Idempotency-Key', unsafe { (&req[ks]).vbytes(kl) })
		x.retryable(true)
	}
	if head_end > 0 && head_end < req.len {
		mut b := x.body()
		unsafe { b.push_many(&req[head_end], req.len - head_end) }
	}
	if x.send(mut el, on_upstream, unsafe { nil }) == .pending {
		return .suspend
	}
	failed(mut out, x.failure())
	x.release()
	return .done
}

// on_upstream is the continuation: advance the exchange; once it is ready,
// relay the upstream's status and body.
fn on_upstream(mut out []u8, fd int, fd_err bool, payload voidptr, worker_state voidptr, mut el core.EventLoop) core.Step {
	mut app := unsafe { &App(worker_state) }
	mut x := app.up.exchange_of(fd) or {
		failed(mut out, .closed)
		return .done
	}
	match x.advance(fd_err, mut el, on_upstream, payload) {
		.pending {
			return .suspend
		}
		.failed {
			failed(mut out, x.failure())
			x.release()
			return .done // not .close (#171)
		}
		.ready {}
	}
	st := x.status()
	core.append_str(mut out, 'HTTP/1.1 ')
	wi(mut out, st)
	core.append_str(mut out, ' \r\n')
	if st == 204 || st == 304 {
		core.append_str(mut out, '\r\n')
	} else {
		ct := x.header_value('content-type')
		if ct.len > 0 {
			core.append_str(mut out, 'Content-Type: ')
			wb(mut out, ct)
			core.append_str(mut out, '\r\n')
		}
		body := x.body_view()
		core.append_str(mut out, 'Content-Length: ')
		wi(mut out, body.len)
		core.append_str(mut out, crlf2)
		wb(mut out, body)
	}
	x.release()
	return .done
}

fn failed(mut out []u8, f upstream.Failure) {
	if f == .timeout {
		core.append_str(mut out, timeout_head)
	} else {
		core.append_str(mut out, failure_head)
	}
	core.append_str(mut out, failure_names[int(f)])
	core.append_str(mut out, crlf2)
}

fn index_of(b []u8, from int, c u8) int {
	for i in from .. b.len {
		if b[i] == c {
			return i
		}
		if b[i] == `\r` {
			return -1
		}
	}
	return -1
}

// field finds the request field `name` (lowercase) in the head req[..end]:
// (start, len) of its value, or (-1, 0).
fn field(req []u8, end int, name string) (int, int) {
	mut i := 0
	for i < end {
		// The start of a line.
		mut j := 0
		for j < name.len && i + j < end {
			mut c := req[i + j]
			if c >= `A` && c <= `Z` {
				c += 32
			}
			if c != name[j] {
				break
			}
			j++
		}
		if j == name.len && i + j < end && req[i + j] == `:` {
			mut s := i + j + 1
			for s < end && (req[s] == ` ` || req[s] == `\t`) {
				s++
			}
			mut e := s
			for e < end && req[e] != `\r` {
				e++
			}
			return s, e - s
		}
		for i < end && req[i] != `\n` {
			i++
		}
		i++
	}
	return -1, 0
}

// index_of_crlf2 is the offset just past the head's blank line, or -1.
fn index_of_crlf2(b []u8) int {
	for i in 3 .. b.len {
		if b[i] == `\n` && b[i - 1] == `\r` && b[i - 2] == `\n` && b[i - 3] == `\r` {
			return i + 1
		}
	}
	return -1
}

fn main() {
	https := os.getenv_opt('UPSTREAM_HTTPS') or { '1' } != '0'
	origin := upstream.Origin{
		host:  os.getenv_opt('UPSTREAM_HOST') or { 'example.com' }
		port:  (os.getenv_opt('UPSTREAM_PORT') or { if https { '443' } else { '80' } }).int()
		https: https
	}
	mut cfg := &tls.Config(unsafe { nil })
	if https {
		// One client config for every worker: the trusted CAs are parsed once.
		cfg = tls.new_client(os.getenv('UPSTREAM_CA'), .full) or { panic(err) }
	}
	mut resolver := upstream.Resolver.new(30_000)!
	resolver.start()
	mut s := server.new_server(server.ServerConfig{
		port:            edge_port
		handler:         edge
		make_state:      fn [origin, cfg, resolver] () voidptr {
			return new_app(origin, cfg, resolver)
		}
		on_worker_start: on_worker_start
	})!
	scheme := if https { 'https' } else { 'http' }
	println('relaying http://localhost:${edge_port}/up/<path> to ${scheme}://${origin.host}:${origin.port}/<path>')
	s.run()
}
